// =====================================================================
//en: FwId.cpp — definition of the baked-in FW identity trailer.
//en:
//en: image_size and sha256 are placeholders (0) — the POST-build script
//en: test_nrf-fota/gen_fw_trailer.py fills them in firmware.hex, located by the
//en: magic. build_number is compile-time from build_info.h (generated by
//en: pre:gen_build_info.py).
//en:
//en: __attribute__((used)) prevents removal by --gc-sections; the .rodata.fwid
//en: section falls under *(.rodata*) in nrf52_common.ld → flash, no ld change.
//sk: FwId.cpp — definícia zapečeného FW identity traileru.
//sk:
//sk: image_size a sha256 sú placeholdery (0) — vyplní ich POST-build skript
//sk: test_nrf-fota/gen_fw_trailer.py vo firmware.hex podľa magicu. build_number
//sk: je compile-time z build_info.h (generuje pre:gen_build_info.py).
//sk:
//sk: __attribute__((used)) zabráni odstráneniu pri --gc-sections; sekcia
//sk: .rodata.fwid spadá pod *(.rodata*) v nrf52_common.ld → flash, bez zmeny ld.
// =====================================================================
#ifdef WITH_LORA_FOTA
#include "FwId.h"
#include "build_info.h"   //en: FW_BUILD_NUMBER (-I test_nrf-fota)

__attribute__((used, section(".rodata.fwid")))
const FwIdTrailer fw_id_trailer = {
    { 'F','K','F','W','I','D','0','1' },  //en: magic
    0,                                     //en: image_size — post-build
    FW_BUILD_NUMBER,                       //en: build_number — compile-time
    { 0 },                                 //en: sha256 — post-build
};
#endif // WITH_LORA_FOTA
