#!/usr/bin/env python3
"""
gen_build_info.py — PlatformIO PRE-build skript pre FOTA test repeatera.

Pri každom builde:
  - inkrementuje build counter v test_nrf-fota/build_number.txt
  - vygeneruje test_nrf-fota/build_info.h s FW_BUILD_NUMBER + FW_BUILD_TIME

MyMesh (pod -DWITH_LORA_FOTA) vypíše "build #N" v heartbeate → po FOTA flash z
neho priamo vidíš, ktorý build beží (NEW musí mať vyššie číslo ako OLD). Toto je
zároveň mechanizmus ktorý zaručí OLD != NEW (build# je súčasť kódu → každý build
je iný → patch nie je prázdny).

Zapojené vo FOTA env (variants/promicro/platformio.ini):
    extra_scripts = pre:test_nrf-fota/gen_build_info.py
    build_flags  += -I test_nrf-fota

DOČASNÉ testovacie lešenie — pre produkčný FOTA build to nie je potrebné.
"""
import datetime
from pathlib import Path

# Cieľe z príkazového riadku (na detekciu `pio run -t nobuild`).
try:
    from SCons.Script import COMMAND_LINE_TARGETS   # type: ignore
except Exception:
    COMMAND_LINE_TARGETS = []

_env = None
try:
    Import("env")              # type: ignore  # PlatformIO SCons kontext
    _env = env                 # type: ignore
    PROJ = Path(env["PROJECT_DIR"])   # type: ignore
except Exception:
    PROJ = Path(__file__).resolve().parent.parent

COUNTER = PROJ / "test_nrf-fota" / "build_number.txt"
HEADER  = PROJ / "test_nrf-fota" / "build_info.h"

# Samostatny CLI rezim (ZephCore CMake pre-build):
#   python gen_build_info.py --out <dir> [--counter-dir <dir>]
# --out: kam zapisat build_info.h; --counter-dir: kde zije build_number.txt
# (default adresar tohto skriptu — zdielane pocitadlo pre repo).
if _env is None and __name__ == "__main__":
    import argparse
    _ap = argparse.ArgumentParser(description="FW build number generator (CLI rezim)")
    _ap.add_argument("--out", required=True, help="adresar pre build_info.h")
    _ap.add_argument("--counter-dir", default=None, help="adresar s build_number.txt")
    _a = _ap.parse_args()
    _cdir = Path(_a.counter_dir) if _a.counter_dir else Path(__file__).resolve().parent
    COUNTER = _cdir / "build_number.txt"
    _outdir = Path(_a.out); _outdir.mkdir(parents=True, exist_ok=True)
    HEADER  = _outdir / "build_info.h"

# NoBuild upload (`pio run -t nobuild -t upload`): NEkompiluje sa, takže build_info.h
# sa nepoužije a na dosku ide POSLEDNÝ skutočne zbuildovaný firmware. Nebumpuj # —
# inak by každý NoBuild upload míňal číslo bez zodpovedajúceho buildu (diery) a
# build_info.h by nesedel s tým, čo je nahraté.
if "nobuild" in COMMAND_LINE_TARGETS:
    print("[build_info] nobuild -> bump # skipped (flashing last build)")
# SCons načíta extra_scripts viackrát za build — inkrementuj LEN raz za beh,
# inak by sa build_info menil počas kompilácie a app flash by nezodpovedal patchu.
elif _env is not None and _env.get("_BUILD_INFO_DONE"):
    pass
else:
    if _env is not None:
        _env["_BUILD_INFO_DONE"] = True

    n = 0
    if COUNTER.exists():
        try:
            n = int(COUNTER.read_text().strip())
        except ValueError:
            n = 0
    n += 1
    COUNTER.write_text(str(n))

    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    HEADER.write_text(
        "// AUTO-GENERATED by test_nrf-fota/gen_build_info.py — NEUPRAVUJ, NEVERZIONUJ\n"
        "#pragma once\n"
        f"#define FW_BUILD_NUMBER {n}\n"
        f'#define FW_BUILD_TIME   "{ts}"\n',
        encoding="utf-8",
    )
    print(f"[build_info] build #{n} @ {ts}  -> {HEADER.name}")
